### ISSUE TITLE
tuist 업데이트 및 firebase crashlytics 적용

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MacC-Team-1010#142]
## 🛠 Issue
tuist 업데이트와 조금 더 편리한 크래시 관리를 위해 firebase crashlytics를 적용합니다.

## 📝 To-do

- [x] firebase crashlytics 적용
- [x] tuist 업데이트

**Comment by jieun0330** [comment]
이거 제가 해봐도 될까요?
